const $=id=>document.getElementById(id);
const KEY='paper-radar-v4', LEGACY_KEY='paper-radar-v3', WATCH='paper-radar-watch-v2', FAV='paper-radar-favorites-v1';
const SB_URL='https://braouypqkiuiwujcyaao.supabase.co';
const SB_KEY='sb_publishable_cTw3hrZD4R3UnZ4fDVI_pw_8Gkzbzfn';
let localPapers=[],cloudPapers=[],papers=[],found=[],watches=[],favorites=new Set(),editingId=null,currentPaper=null,currentView='overview',quickFilter='all',libraryMode='table',selectedDays=90;
const fields=['title','authors','year','journal','doi','url','category','relevance','status','keywords','notes'];
function uid(){return crypto.randomUUID?crypto.randomUUID():'p'+Date.now()+Math.random()}
function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toast(s){let t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2300)}
function ident(p){return(p.doi||'').trim().toLowerCase()||(p.title||'').trim().toLowerCase()}
function norm(p={}){return{id:p.id||uid(),title:(p.title||'').trim(),authors:(p.authors||'').trim(),year:String(p.year||'').trim(),journal:(p.journal||'').trim(),doi:(p.doi||'').trim(),url:(p.url||'').trim(),category:(p.category||'未分类').trim()||'未分类',relevance:['高','中','低'].includes(p.relevance)?p.relevance:'中',status:['待读','粗读','精读'].includes(p.status)?p.status:'待读',keywords:(p.keywords||'').trim(),notes:(p.notes||'').trim(),origin:p.origin||'local',discoveredAt:p.discoveredAt||'',publishedAt:p.publishedAt||''}}
function loadLocal(){try{let raw=localStorage.getItem(KEY);if(!raw)raw=localStorage.getItem(LEGACY_KEY)||'[]';localPapers=(JSON.parse(raw)||[]).filter(x=>!String(x.id||'').startsWith('cloud-')).map(x=>norm({...x,origin:'local'}))}catch{localPapers=[]}try{watches=JSON.parse(localStorage.getItem(WATCH)||'[]')||[]}catch{watches=[]}try{favorites=new Set(JSON.parse(localStorage.getItem(FAV)||'[]')||[])}catch{favorites=new Set()}const theme=localStorage.getItem('paper-radar-theme')||'light';document.documentElement.dataset.theme=theme}
function persist(){localStorage.setItem(KEY,JSON.stringify(localPapers));localStorage.setItem(KEY+'.updated',new Date().toISOString());rebuild()}
function persistWatch(){localStorage.setItem(WATCH,JSON.stringify(watches));renderWatches()}
function persistFav(){localStorage.setItem(FAV,JSON.stringify([...favorites]));renderAll()}
function rebuild(){const seen=new Set();papers=[...cloudPapers,...localPapers].filter(p=>{let k=ident(p);if(!k||seen.has(k))return false;seen.add(k);return true});renderAll()}
async function loadCloud(showToast=false){$('cloudMini').textContent='同步中…';$('cloudStatusBig').textContent='正在读取云端论文';try{const url=SB_URL+'/rest/v1/papers?select=*&order=discovered_at.desc&limit=500';const r=await fetch(url,{headers:{apikey:SB_KEY,Authorization:'Bearer '+SB_KEY}});if(!r.ok)throw Error(r.status);const rows=await r.json();cloudPapers=rows.map(x=>norm({id:'cloud-'+x.id,title:x.title,authors:x.authors,year:x.publication_year,journal:x.journal,doi:x.doi,url:x.url,category:x.category,relevance:x.relevance,status:x.reading_status,keywords:x.keywords,notes:x.notes,origin:'cloud',discoveredAt:x.discovered_at,publishedAt:x.published_at}));$('cloudMini').textContent=`已连接 · ${cloudPapers.length} 篇`;$('cloudStatusBig').textContent=`云端已同步 ${cloudPapers.length} 篇`;if(showToast)toast(`云端已刷新：${cloudPapers.length} 篇`);rebuild()}catch(e){console.error(e);$('cloudMini').textContent='连接失败';$('cloudStatusBig').textContent='云端读取失败，使用本地库';if(showToast)toast('云端刷新失败');rebuild()}}
function renderAll(){renderStats();renderOverview();renderLibrary();renderWatches();$('navPaperCount').textContent=papers.length;$('navWatchCount').textContent=watches.length}
function renderStats(){$('sTotal').textContent=papers.length;$('sHigh').textContent=papers.filter(x=>x.relevance==='高').length;$('sTodo').textContent=papers.filter(x=>x.status==='待读').length;$('sFav').textContent=papers.filter(x=>favorites.has(ident(x))).length;let u=localStorage.getItem(KEY+'.updated');$('lastUpdate').textContent=cloudPapers.length?`云端 ${cloudPapers.length} + 本地 ${localPapers.length}`:(u?'本地 '+new Date(u).toLocaleDateString():'等待同步')}
function renderOverview(){let cats={};papers.forEach(p=>cats[p.category]=(cats[p.category]||0)+1);let top=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,6),max=top[0]?.[1]||1;$('categoryBars').innerHTML=top.length?top.map(([k,v])=>`<div class="bar-row"><label title="${esc(k)}">${esc(k)}</label><div class="bar-track"><div class="bar-fill" style="width:${Math.max(8,v/max*100)}%"></div></div><b>${v}</b></div>`).join(''):'<div class="empty">暂无数据</div>';let years={};papers.forEach(p=>{let y=parseInt(p.year);if(y>1900)years[y]=(years[y]||0)+1});let ys=Object.entries(years).sort((a,b)=>a[0]-b[0]).slice(-10),ym=Math.max(...ys.map(x=>x[1]),1);$('yearChart').innerHTML=ys.map(([y,v])=>`<div class="year-col" title="${y}: ${v}篇"><div class="year-bar" style="height:${Math.max(8,v/ym*100)}%"></div><small>${y.slice(2)}</small></div>`).join('');$('yearRangeText').textContent=ys.length?`${ys[0][0]}—${ys.at(-1)[0]}`:'—';let recent=[...papers].sort((a,b)=>dateScore(b)-dateScore(a)).slice(0,6);$('recentList').innerHTML=recent.length?recent.map((p,i)=>`<div class="recent-item" onclick="openDrawerById('${p.id}')"><span class="num">${String(i+1).padStart(2,'0')}</span><div><b>${esc(p.title)}</b><small>${esc(p.journal||p.category)} · ${esc(p.year||'—')}</small></div><time>${p.origin==='cloud'?'云端':'本地'}</time></div>`).join(''):'<div class="empty">暂无论文</div>';$('focusChips').innerHTML=top.slice(0,8).map(([k,v])=>`<button class="focus-chip" onclick="focusCategory('${encodeURIComponent(k)}')">${esc(k)} · ${v}</button>`).join('')||'<span class="tiny">暂无研究方向</span>'}
function dateScore(p){return Date.parse(p.discoveredAt||p.publishedAt||`${p.year||1900}-01-01`)||0}
function getFiltered(){let q=$('q')?.value.trim().toLowerCase()||'',c=$('cat')?.value||'',r=$('rel')?.value||'',s=$('st')?.value||'',src=$('sourceFilter')?.value||'';let arr=papers.filter(p=>(!q||[p.title,p.authors,p.journal,p.doi,p.keywords,p.notes,p.category].join(' ').toLowerCase().includes(q))&&(!c||p.category===c)&&(!r||p.relevance===r)&&(!s||p.status===s)&&(!src||p.origin===src));if(quickFilter==='high')arr=arr.filter(p=>p.relevance==='高');if(quickFilter==='favorite')arr=arr.filter(p=>favorites.has(ident(p)));if(quickFilter==='recent'){let lim=Date.now()-30*864e5;arr=arr.filter(p=>dateScore(p)>=lim)}let sort=$('sortBy')?.value||'new';arr.sort(sort==='year'?(a,b)=>(+b.year||0)-(+a.year||0):sort==='title'?(a,b)=>a.title.localeCompare(b.title):((a,b)=>dateScore(b)-dateScore(a)));return arr}
function renderLibrary(){if(!$('cat'))return;let old=$('cat').value,cats=[...new Set(papers.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN'));$('cat').innerHTML='<option value="">全部分类</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join('');$('cat').value=cats.includes(old)?old:'';let rows=getFiltered();$('count').textContent=rows.length+' 篇';$('activeFilterText').textContent=quickFilter==='all'?'当前筛选结果':quickFilter==='high'?'高相关论文':quickFilter==='favorite'?'收藏论文':'近30天发现';$('tb').innerHTML=rows.map(p=>paperRow(p)).join('');$('paperGrid').innerHTML=rows.map(p=>paperCard(p)).join('');$('empty').style.display=rows.length?'none':'block';$('tableWrap').style.display=libraryMode==='table'?'block':'none';$('paperGrid').style.display=libraryMode==='card'?'grid':'none'}
function paperRow(p){let fav=favorites.has(ident(p));return`<tr><td><button class="fav-btn ${fav?'on':''}" onclick="toggleFav('${p.id}',event)">${fav?'★':'☆'}</button></td><td><div class="paper-title" onclick="openDrawerById('${p.id}')">${esc(p.title)}</div><div class="meta">${esc(p.authors||'作者未录入')}${p.doi?' · '+esc(p.doi):''}</div></td><td>${esc(p.year||'—')}</td><td>${esc(p.category)}</td><td><span class="tag ${p.relevance==='高'?'high':p.relevance==='中'?'mid':'low'}">${p.relevance}</span></td><td>${p.status}</td><td>${esc(p.journal||'—')}</td><td><span class="source-badge ${p.origin}">${p.origin==='cloud'?'云端':'本地'}</span></td></tr>`}
function paperCard(p){let fav=favorites.has(ident(p));return`<article class="paper-card" onclick="openDrawerById('${p.id}')"><div class="paper-card-top"><span class="source-badge ${p.origin}">${p.origin==='cloud'?'云端':'本地'}</span><button class="fav-btn ${fav?'on':''}" onclick="toggleFav('${p.id}',event)">${fav?'★':'☆'}</button></div><h3>${esc(p.title)}</h3><div class="meta">${esc(p.authors||'未知作者')}</div><div class="paper-card-footer"><span>${esc(p.year||'—')} · ${esc(p.category)}</span><span class="tag ${p.relevance==='高'?'high':p.relevance==='中'?'mid':'low'}">${p.relevance}</span></div></article>`}
window.toggleFav=(id,e)=>{e?.stopPropagation();let p=papers.find(x=>x.id===id);if(!p)return;let k=ident(p);favorites.has(k)?favorites.delete(k):favorites.add(k);persistFav()};window.openDrawerById=id=>{let p=papers.find(x=>x.id===id);if(p)openDrawer(p)};
function openDrawer(p){currentPaper=p;$('drawer').classList.add('open');$('drawerSource').textContent=p.origin==='cloud'?'云端自动抓取':'本地论文';$('drawerSource').className='source-badge '+p.origin;$('drawerRel').textContent=p.relevance;$('drawerRel').className='rel-badge '+(p.relevance==='高'?'high':p.relevance==='中'?'mid':'low');$('drawerTitle').textContent=p.title;$('drawerAuthors').textContent=p.authors||'作者未录入';$('drawerYear').textContent=p.year||'—';$('drawerJournal').textContent=p.journal||'—';$('drawerCat').textContent=p.category||'—';$('drawerDoi').textContent=p.doi||'—';$('drawerKeywords').innerHTML=(p.keywords||'').split(/[,，;；]/).filter(Boolean).slice(0,12).map(x=>`<span>${esc(x.trim())}</span>`).join('')||'<span>暂无关键词</span>';$('drawerNotes').textContent=p.notes||'暂无备注';$('drawerOpen').style.display=p.url?'inline-flex':'none';if(p.url)$('drawerOpen').href=p.url;$('drawerFav').textContent=favorites.has(ident(p))?'★ 已收藏':'☆ 收藏';$('drawerCopy').style.display=p.origin==='cloud'?'inline-flex':'none'}
function closeDrawer(){$('drawer').classList.remove('open');currentPaper=null}
$('drawerClose').onclick=$('drawerOverlay').onclick=closeDrawer;$('drawerFav').onclick=()=>{if(!currentPaper)return;let k=ident(currentPaper);favorites.has(k)?favorites.delete(k):favorites.add(k);persistFav();$('drawerFav').textContent=favorites.has(k)?'★ 已收藏':'☆ 收藏'};$('drawerCopy').onclick=()=>{if(!currentPaper)return;let copy=norm({...currentPaper,id:uid(),origin:'local',notes:(currentPaper.notes||'')+'\n已从云端复制到本地。'});let r=mergeLocal([copy]);toast(r.added?'已复制到本地库':'本地已存在此论文')};
function mergeLocal(arr){let seen=new Set(localPapers.map(ident)),added=0,skip=0;for(let x of arr){let p=norm({...x,origin:'local'}),k=ident(p);if(!p.title||!k||seen.has(k)){skip++;continue}localPapers.unshift(p);seen.add(k);added++}persist();return{added,skip}}
function openModal(p=null){editingId=p?.id||null;$('mt').textContent=p?'编辑本地论文':'添加本地论文';['Title','Authors','Year','Journal','Doi','Url','Cat','Rel','St','Keys','Notes'].forEach((k,i)=>$('f'+k).value=p?.[fields[i]]||(['Rel','St'].includes(k)?(k==='Rel'?'中':'待读'):'') );$('modal').classList.add('open')}
function closeModal(){$('modal').classList.remove('open')}
$('add').onclick=$('addTop').onclick=()=>openModal();$('cancel').onclick=$('modalCancel2').onclick=closeModal;$('save').onclick=()=>{let v={id:editingId||uid(),origin:'local'};['Title','Authors','Year','Journal','Doi','Url','Cat','Rel','St','Keys','Notes'].forEach((k,i)=>v[fields[i]]=$('f'+k).value);v=norm(v);if(!v.title)return alert('请填写论文题目');let i=localPapers.findIndex(x=>x.id===v.id);i>=0?localPapers[i]=v:localPapers.unshift(v);persist();closeModal();toast('已保存到本地论文库')};
function switchView(v){currentView=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('sidebar').classList.remove('open');if(v==='library')renderLibrary()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');
$('themeToggle').onclick=()=>{let t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;localStorage.setItem('paper-radar-theme',t)};$('refreshCloud').onclick=$('syncNowOverview').onclick=()=>loadCloud(true);
['q','cat','rel','st','sourceFilter','sortBy'].forEach(id=>$(id).addEventListener(id==='q'?'input':'change',renderLibrary));$('clearFilters').onclick=()=>{$('q').value='';$('cat').value='';$('rel').value='';$('st').value='';$('sourceFilter').value='';$('sortBy').value='new';quickFilter='all';document.querySelectorAll('#quickFilters .chip').forEach(x=>x.classList.toggle('active',x.dataset.qf==='all'));renderLibrary()};document.querySelectorAll('#quickFilters .chip').forEach(b=>b.onclick=()=>{quickFilter=b.dataset.qf;document.querySelectorAll('#quickFilters .chip').forEach(x=>x.classList.toggle('active',x===b));renderLibrary()});$('tableViewBtn').onclick=()=>{libraryMode='table';$('tableViewBtn').classList.add('active');$('cardViewBtn').classList.remove('active');renderLibrary()};$('cardViewBtn').onclick=()=>{libraryMode='card';$('cardViewBtn').classList.add('active');$('tableViewBtn').classList.remove('active');renderLibrary()};document.querySelectorAll('.stat').forEach(b=>b.onclick=()=>{switchView('library');let f=b.dataset.filter;quickFilter=f==='all'?'all':f==='high'?'high':f==='favorite'?'favorite':'all';if(f==='todo')$('st').value='待读';document.querySelectorAll('#quickFilters .chip').forEach(x=>x.classList.toggle('active',x.dataset.qf===quickFilter));renderLibrary()});window.focusCategory=encoded=>{let c=decodeURIComponent(encoded);switchView('library');$('cat').value=c;renderLibrary()};
function before(days){return new Date(Date.now()-days*864e5).toISOString().slice(0,10)}
function mapOA(x,q){let authors=(x.authorships||[]).slice(0,6).map(a=>a.author?.display_name).filter(Boolean).join('; '),journal=x.primary_location?.source?.display_name||'OpenAlex',doi=(x.doi||'').replace(/^https?:\/\/doi\.org\//i,''),url=x.primary_location?.landing_page_url||x.doi||x.id||'',concepts=(x.concepts||[]).slice(0,5).map(c=>c.display_name).filter(Boolean).join(', '),parts=q.toLowerCase().split(/\s+/).filter(Boolean),hay=((x.display_name||'')+' '+concepts).toLowerCase(),hits=parts.filter(t=>hay.includes(t)).length;return norm({title:x.display_name,authors,year:x.publication_year,journal,doi,url,category:'实时检索',relevance:hits>=Math.max(2,Math.ceil(parts.length/2))?'高':'中',status:'待读',keywords:concepts||q,notes:'实时检索来源：OpenAlex；检索词：'+q,origin:'search',publishedAt:x.publication_date})}
async function searchOA(q,days,lim){let url=`https://api.openalex.org/works?search=${encodeURIComponent(q)}&filter=from_publication_date:${before(+days)},has_abstract:true&sort=publication_date:desc&per-page=${lim}`;let r=await fetch(url);if(!r.ok)throw Error(r.status);return(await r.json()).results||[]}
function renderFound(){$('results').innerHTML=found.length?found.map((p,i)=>`<article class="result-card"><div><span class="source-badge cloud">OpenAlex</span> <span class="rel-badge ${p.relevance==='高'?'high':'mid'}">${p.relevance}相关</span></div><h3>${esc(p.title)}</h3><div class="meta">${esc(p.authors||'未知作者')} · ${esc(p.year||'—')} · ${esc(p.journal||'—')}</div><div class="result-actions"><button class="btn soft" onclick="previewFound(${i})">查看详情</button><button class="btn primary" onclick="importOne(${i})">导入本地</button></div></article>`).join(''):'<div class="empty">暂无检索结果。输入关键词后开始扫描。</div>';$('importAll').disabled=!found.length}
async function runFind(q=$('findQ').value){q=q.trim();if(!q)return alert('请输入检索关键词');$('loading').style.display='flex';$('findBtn').disabled=true;try{let raw=await searchOA(q,selectedDays,$('limit').value);found=raw.map(x=>mapOA(x,q)).filter(x=>x.title);renderFound();$('findMeta').innerHTML=`关键词：<b>${esc(q)}</b> · ${selectedDays}天 · 找到 <b>${found.length}</b> 篇`;toast(`扫描完成：${found.length} 篇`)}catch(e){console.error(e);$('findMeta').textContent='检索失败，可能是网络或公开接口暂不可用。'}finally{$('loading').style.display='none';$('findBtn').disabled=false}}
$('findBtn').onclick=()=>runFind();$('clearFound').onclick=()=>{found=[];renderFound();$('findMeta').textContent='已清空检索结果'};$('importAll').onclick=()=>{let r=mergeLocal(found);toast(`新增 ${r.added} 篇，跳过 ${r.skip} 篇`)};window.importOne=i=>{let r=mergeLocal([found[i]]);toast(r.added?'已导入本地库':'本地已存在')};window.previewFound=i=>openDrawer({...found[i],id:'found-'+i,origin:'cloud'});document.querySelectorAll('#daySeg button').forEach(b=>b.onclick=()=>{selectedDays=+b.dataset.days;document.querySelectorAll('#daySeg button').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('#presetQueries button').forEach(b=>b.onclick=()=>{$('findQ').value=b.dataset.query;runFind()});
function renderWatches(){$('navWatchCount').textContent=watches.length;$('watchList').innerHTML=watches.length?watches.map(w=>`<article class="watch-card card"><span class="section-label">LOCAL WATCH</span><h3>${esc(w.q)}</h3><p>${w.last?'上次刷新：'+new Date(w.last).toLocaleString():'尚未刷新'}</p><div class="watch-card-actions"><button class="btn soft" onclick="runWatch('${w.id}')">立即扫描</button><button class="btn soft" onclick="rmWatch('${w.id}')">删除</button></div></article>`).join(''):'<div class="card panel empty">还没有本地监控词。</div>'}
$('watchAdd').onclick=()=>{let q=$('watchQ').value.trim();if(!q)return;watches.unshift({id:uid(),q,last:null});$('watchQ').value='';persistWatch();toast('监控词已保存')};window.rmWatch=id=>{watches=watches.filter(x=>x.id!==id);persistWatch()};window.runWatch=async id=>{let w=watches.find(x=>x.id===id);if(!w)return;switchView('discover');$('findQ').value=w.q;await runFind(w.q);w.last=new Date().toISOString();persistWatch()};$('autoWatch').checked=localStorage.getItem(WATCH+'.auto')==='1';$('autoWatch').onchange=e=>localStorage.setItem(WATCH+'.auto',e.target.checked?'1':'0');
function download(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}function csvEsc(v){v=String(v??'');return/[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}$('backup').onclick=()=>download('paper-radar-local-backup.json',JSON.stringify(localPapers,null,2),'application/json');$('exportCsv').onclick=()=>{let cs=fields;download('paper-radar-papers.csv','\ufeff'+[cs.join(','),...papers.map(p=>cs.map(c=>csvEsc(p[c])).join(','))].join('\n'),'text/csv;charset=utf-8')};$('restore').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let d=JSON.parse(await f.text());if(!Array.isArray(d))throw 0;localPapers=d.map(x=>norm({...x,origin:'local'}));persist();toast('本地备份已恢复')}catch{alert('JSON 格式不正确')}e.target.value=''};
function csvParse(t){let a=[],row=[],v='',q=false;for(let i=0;i<t.length;i++){let c=t[i],n=t[i+1];if(q){if(c==='"'&&n==='"'){v+='"';i++}else if(c==='"')q=false;else v+=c}else if(c==='"')q=true;else if(c===','){row.push(v);v=''}else if(c==='\n'){row.push(v);a.push(row);row=[];v=''}else if(c!=='\r')v+=c}row.push(v);if(row.some(Boolean))a.push(row);return a}const alias={title:['title','题目','标题','论文题目'],authors:['authors','author','作者'],year:['year','年份'],journal:['journal','期刊','来源'],doi:['doi','pmid','doi/pmid'],url:['url','link','链接'],category:['category','分类','方向'],relevance:['relevance','相关度'],status:['status','状态','阅读状态'],keywords:['keywords','关键词'],notes:['notes','备注','摘要']};function key(s){s=String(s).trim().toLowerCase().replace(/[\s_\-：:（）()]/g,'');for(const[k,a]of Object.entries(alias))if(a.some(x=>x.toLowerCase().replace(/[\s_\-：:（）()]/g,'')===s))return k;return null}$('csv').onchange=async e=>{let f=e.target.files[0];if(!f)return;let rows=csvParse(await f.text()),h=rows[0].map(key),r=mergeLocal(rows.slice(1).map(row=>{let p={};h.forEach((k,i)=>{if(k)p[k]=row[i]||''});return p}));toast(`CSV 新增 ${r.added} 篇，跳过 ${r.skip} 篇`);e.target.value=''};function txt(n){return Array.from(n.getElementsByTagNameNS('*','t')).map(x=>x.textContent||'').join('').trim()}$('docx').onchange=async e=>{let f=e.target.files[0];if(!f)return;if(!/\.docx$/i.test(f.name))return alert('请使用 .docx 文件');try{let z=await JSZip.loadAsync(f),entry=z.file('word/document.xml');if(!entry)throw 0;let x=await entry.async('string'),d=new DOMParser().parseFromString(x,'application/xml'),out=[];for(const t of d.getElementsByTagNameNS('*','tbl')){let rs=Array.from(t.getElementsByTagNameNS('*','tr')).map(tr=>Array.from(tr.getElementsByTagNameNS('*','tc')).map(txt));if(rs.length<2)continue;let h=rs[0].map(key);if(!h.includes('title'))continue;out.push(...rs.slice(1).map(row=>{let p={};h.forEach((k,i)=>{if(k)p[k]=row[i]||''});return p}))}if(!out.length){let cur={};for(const line of Array.from(d.getElementsByTagNameNS('*','p')).map(txt)){let m=line.match(/^\s*([^:：]{1,20})[:：]\s*(.+)$/);if(!m)continue;let k=key(m[1]);if(!k)continue;if(k==='title'&&cur.title){out.push(cur);cur={}}cur[k]=m[2]}if(cur.title)out.push(cur)}if(!out.length)return alert('没有识别到论文记录。建议 Word 使用表格格式。');let r=mergeLocal(out);toast(`Word 新增 ${r.added} 篇，跳过 ${r.skip} 篇`)}catch{alert('Word 解析失败，请确认是有效 .docx 文件')}e.target.value=''};
function openCommand(q=''){$('command').classList.add('open');$('commandInput').value=q;$('commandInput').focus();renderCommand(q)}function closeCommand(){$('command').classList.remove('open')}function renderCommand(q){q=q.trim().toLowerCase();let rs=(q?papers.filter(p=>[p.title,p.authors,p.keywords,p.doi].join(' ').toLowerCase().includes(q)):papers).slice(0,12);$('commandResults').innerHTML=rs.map(p=>`<div class="command-item" onclick="commandOpen('${p.id}')"><b>${esc(p.title)}</b><small>${esc(p.authors||p.journal||p.category)}</small></div>`).join('')||'<div class="empty">没有匹配论文</div>'}window.commandOpen=id=>{closeCommand();openDrawerById(id)};$('commandInput').oninput=e=>renderCommand(e.target.value);$('globalSearch').onfocus=()=>openCommand($('globalSearch').value);$('globalSearch').oninput=e=>{if($('command').classList.contains('open'))renderCommand(e.target.value)};$('command').onclick=e=>{if(e.target===$('command'))closeCommand()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape'){closeCommand();closeDrawer();closeModal()}});
loadLocal();rebuild();renderFound();loadCloud();if($('autoWatch').checked&&watches[0])setTimeout(()=>runWatch(watches[0].id),900);